Todo 001
sschanzer/todo_site pull request #1
Opened 2023-02-02 18:34 UTC by sschanzer

2023-02-02 18:35 UTC, sschanzer commented
Acceptance Criteria:
Give a user opens the app
When the home page is shown
Then a list of all tasks should be displayed

2023-02-03 07:39 UTC, Kotauror requested changes

2023-02-03 07:39 UTC, Kotauror commented on README.md
> +```
This is a really good Readme file! It lists everything that a person needs to run a project. It's better than some of the real projects that I've seen, for real. 

I do have one comment though, but it's a stretch goal and that intuition comes with experience. 
I'm sure this information can be useful for a junior coder, but in general, the Readme doesn't have to include the exact commands that one needs to run in order to achieve a purpose if you listed that purpose properly and especially if the commands are very basic. 

For example, a person can create and open a file in different ways, not only with `touch` and `code`, so it's totally enough to just say `Create .env file with `SECRET_KEY` from backend/settings.py`. 

Also, if you want to make sure that someone follows your exact structure of the `.env` file, a popular practice is to include `.env.example`, that a user then renames to `.env` and adds the real values.

2023-02-03 07:39 UTC, Kotauror commented on backend/backend/asgi.py
> +"""
Do you need to commit the `backend/backend/__pycache__/*` files?

2023-02-03 07:39 UTC, Kotauror commented on backend/todo_app/admin.py
> +from django.contrib import admin
Do you need to commit the backend/todo_app/__pycache__/* files?

2023-02-03 07:39 UTC, Kotauror commented on backend/todo_app/fixtures/data.json
> +]
it's a detail - not sure if you know, but this red minus says that there is no empty line at the end of the file. It's a styling issue, nothing more, but having a formatter in your IDE could help you to add them each time you save/commit etc. so that you don't have to remember about doing it manually.

2023-02-03 07:39 UTC, Kotauror commented on backend/todo_app/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
Wow, I didn't know such thing as `BigAutoField` exists and I've used Django before, thanks! It looks like you'll have a lot of tasks on your list ;) 

> BigAutoField is a 64-bit integer, much like an AutoField except that it is guaranteed to fit numbers from 1 to 9223372036854775807. One can create a BigAutoField using the following syntax,
([source](https://www.geeksforgeeks.org/bigautofield-django-models/))

2023-02-03 07:39 UTC, Kotauror commented on backend/todo_app/views.py
> +    # return HttpResponse("<h1>HOMEPAGE</h1>")
Remember to remove the lines that don't matter anymore. Same goes for #17

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/App.tsx
> +  const [completedTasks, setCompletedTasks]:[myTasks[], (completedTasks:myTasks[]) => void] = React.useState<myTasks[]>([])
You should be able to use just `useState`, without `React.`, as you explicitly imported `useState` on line 1. Also, see line #30

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/App.tsx
> +      setPendingTasks(response.pending)
Now here is the first place where I'd recommend making changes to your code. 

Firstly, there is naming - `getResponse` is a name that doesn't tell us much about its purpose. When the application grows and you start adding and removing tasks, you will have requests and responses too and this name will already prove to be problematic. Try coming up with something more descriptive - what is this whole function doing - cause it's not only getting the response, this is up to `getTasks`, it's doing more on lines #37 and #38.

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/App.tsx
> +
try adding a formatter to your IDE, for example, Prettier. It will help you get rid of empty lines etc.

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/App.tsx
> +  //   </div>
delete old code.

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/components/Header.tsx
> +    // function handleAddTask() {
delete old code

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/components/Header.tsx
> +
this needs proper tabbing :) Formatter will do it in a split second.

2023-02-03 07:39 UTC, Kotauror commented on frontend/src/tests/App.test.tsx
> +describe("Get the data from the database", () => {
I'd say "get the _tasks_" - _data_ is not clear enough.

2023-02-03 15:15 UTC, nadiacollado commented on frontend/src/App.tsx
> +  const [selected, setSelected] = useState<number[]>([])
I would try to keep UI changes that aren't yet needed to a minimum. So, this ticket calls for rendering a task list, whether that includes selection or not is debatable, but if you want to keep the selection checkbox in this ticket, I would change this to `selectedTask` and `setSelectedTask` so it's more explicit about what it's selecting :)

2023-02-03 15:15 UTC, nadiacollado commented on frontend/src/App.tsx
> +  const [completedTasks, setCompletedTasks]:[myTasks[], (completedTasks:myTasks[]) => void] = React.useState<myTasks[]>([])
This can be written like this which is a little cleaner:
`const [completedTasks, setCompletedTasks] = useState<myTasks[]>([])`

2023-02-03 15:15 UTC, nadiacollado commented on frontend/src/App.tsx
> +  const [pendingTasks, setPendingTasks]:[myTasks[], (pendingTasks:myTasks[]) => void] = React.useState<myTasks[]>([])
Same comment as above

2023-02-03 15:15 UTC, nadiacollado commented on frontend/src/components/Tasks.tsx
> +interface IdProps{
Just out of curiosity, why is interface called `IdProps` -- what is the `Id` portion referencing to?

2023-02-03 15:15 UTC, nadiacollado commented on frontend/src/components/Tasks.tsx
> +
This file needs some formatting as well :)

2023-02-03 15:15 UTC, nadiacollado commented on frontend/src/tests/App.test.tsx
> +describe("Get the data from the database", () => {
I have generally stuck to the following convention when writing tests. I think that it reads a lot easier

```
describe("App", () => {
  describe("getTasks()", () => {
    test("returns tasks from database" , () => {
        \\ code here 
    })
})
```

2023-02-04 19:02 UTC, sschanzer commented on README.md
> +```
Cool, I like the idea of including an example env file, so I went ahead and made one.

2023-02-04 19:06 UTC, sschanzer commented on backend/backend/asgi.py
> +"""
The __pycache__ file is shows up in the backend folder... https://github.com/sschanzer/todo_site/tree/TODO-001/backend/backend. I committed everything that wasn't in my .gitignore, so it should be there. Let me know if you see it.

2023-02-04 19:06 UTC, sschanzer commented on backend/todo_app/admin.py
> +from django.contrib import admin
Should be there. https://github.com/sschanzer/todo_site/tree/TODO-001/backend/todo_app

2023-02-04 19:07 UTC, sschanzer commented on backend/todo_app/fixtures/data.json
> +]
I thought I had a formatter running automatically, but apparently not. I'll run it before commits from now on.

2023-02-04 19:08 UTC, sschanzer commented on backend/todo_app/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
BigAutoField was generated automatically after I make migrations. I'm not sure why django defaults to that.

2023-02-04 19:09 UTC, sschanzer commented on backend/todo_app/views.py
> +    # return HttpResponse("<h1>HOMEPAGE</h1>")
I got rid of them, but is there a way to keep comments so I can still look at them?

2023-02-04 19:12 UTC, sschanzer commented on frontend/src/App.tsx
> +  const [completedTasks, setCompletedTasks]:[myTasks[], (completedTasks:myTasks[]) => void] = React.useState<myTasks[]>([])
I updated this. I was confused, I thought it was a typescript thing for some reason.

2023-02-04 19:17 UTC, sschanzer commented on frontend/src/App.tsx
> +      setPendingTasks(response.pending)
Makes sense. I changed it to getResponseFromGetTasks.

2023-02-04 19:18 UTC, sschanzer commented on frontend/src/App.tsx
> +
I ran prettier on the base directory, so hopefully it will have a cleaner format on the next commit.

2023-02-04 19:19 UTC, sschanzer commented on frontend/src/App.tsx
> +  //   </div>
Deleted

2023-02-04 19:20 UTC, sschanzer commented on frontend/src/components/Header.tsx
> +    // function handleAddTask() {
This function is going to handle the add task functionality in TODO-002, but I deleted it for this branch.

2023-02-04 19:22 UTC, sschanzer commented on frontend/src/components/Header.tsx
> +
I thought I ran prettier on all files, but this is still unindented... I don't know why it isn't working...

2023-02-04 19:23 UTC, sschanzer commented on frontend/src/tests/App.test.tsx
> +describe("Get the data from the database", () => {
Changed

2023-02-04 19:27 UTC, sschanzer commented on frontend/src/App.tsx
> +export async function getTasks():Promise<responseTasks> {
This should just return all the tasks. I'm not sure what you mean by returning one task list in the response. What should I be returning here and how should it be returned?

2023-02-04 19:30 UTC, sschanzer commented on frontend/src/App.tsx
> +  const [selected, setSelected] = useState<number[]>([])
That's a good call. I've updated the hook names.

2023-02-04 19:33 UTC, sschanzer commented on frontend/src/App.tsx
> +  const [completedTasks, setCompletedTasks]:[myTasks[], (completedTasks:myTasks[]) => void] = React.useState<myTasks[]>([])
REALLY!? That's super helpful to know! I was really confused when I was writing these hooks, I thought it was some goofy typescript thing! It has been updated!

2023-02-04 19:35 UTC, sschanzer commented on frontend/src/App.tsx
> +  const [pendingTasks, setPendingTasks]:[myTasks[], (pendingTasks:myTasks[]) => void] = React.useState<myTasks[]>([])
Changed

2023-02-04 19:37 UTC, sschanzer commented on frontend/src/components/Tasks.tsx
> +interface IdProps{
Its for future use. It references the id of the task in the database so I can filter through and organize the tasks and know which ones were selected or not.

2023-02-04 19:37 UTC, sschanzer commented on frontend/src/components/Tasks.tsx
> +
I tried running prettier, but it doesn't seem to be working...

2023-02-06 17:28 UTC, sschanzer commented on backend/backend/asgi.py
> +"""
Ah, I understand now. No I don't.

2023-02-06 18:41 UTC, nadiacollado commented on frontend/src/App.tsx
> +export async function getTasks():Promise<responseTasks> {
Gotcha, sorry, misunderstood what was happening here. This is fine. Another way of doing this would be to return the list of task objects without filtering them out in the backend by their status, so you'd only have one list of `ITask` objects to add to state. This way you wouldn't have to add another interface for the response. You'd simply return `ITask[]` in `getTasks`. Then you'd do the filtering at some point after setting the task list, saving the output to a variable, and use that in the return statement.

2023-02-06 20:16 UTC, nadiacollado commented on README.md
> +### Runing the Tests
Typo: "Running"

2023-02-06 20:18 UTC, nadiacollado commented on README.md
> +To run the tests after cloning the repo and creating your .env file with your secret key included, cd into backend and run the following:
I'd simplify this: `In the backend directory, run the following:` or something to that effect.

2023-02-06 20:22 UTC, nadiacollado commented on frontend/src/App.tsx
> +export interface myTasks {
Interfaces are often prepended with an `I` so I would rename this to `ITask`, also singular because it represents one task.

2023-02-06 20:30 UTC, nadiacollado commented on frontend/src/components/Tasks.tsx
> +
Did you add it as the default formatter in workspace settings? You can also have it so that it runs whenever you save. 
<img width="921" alt="Screen Shot 2023-02-06 at 3 29 54 PM" src="https://user-images.githubusercontent.com/69662091/217078404-4ebd076c-2c6b-4cea-bf4b-f8a087932769.png">
<img width="911" alt="Screen Shot 2023-02-06 at 3 30 05 PM" src="https://user-images.githubusercontent.com/69662091/217078411-2c26c6c7-0ad5-4348-8ecf-4eb6cf2b4a0e.png">

2023-02-06 20:34 UTC, nadiacollado commented on frontend/src/components/Tasks.tsx
> +export const Tasks: React.FC<IdProps> = ({task, selected, setSelected}) => {
I would rename this component to its singular form (`Task`) because it's only rendering one task  not a list of tasks

2023-02-06 20:45 UTC, nadiacollado commented on frontend/src/components/Tasks.tsx
> +interface IdProps{
Hmm I would change this to`TaskProps`. `IdProps` is a bit unclear.

2023-02-06 21:26 UTC, sschanzer commented on backend/todo_app/views.py
> +    completedTasks = filter(lambda x: x['completed'] == True, tasks)
Changed

2023-02-06 21:26 UTC, sschanzer commented on frontend/src/tests/App.test.tsx
> +describe("Get the data from the database", () => {
changed

2023-02-06 21:27 UTC, sschanzer commented on README.md
> +### Runing the Tests
Changed

2023-02-06 21:27 UTC, sschanzer commented on README.md
> +To run the tests after cloning the repo and creating your .env file with your secret key included, cd into backend and run the following:
Changed

2023-02-06 21:31 UTC, sschanzer commented on frontend/src/App.tsx
> +export interface myTasks {
Changed

2023-02-06 21:32 UTC, sschanzer commented on frontend/src/components/Tasks.tsx
> +export const Tasks: React.FC<IdProps> = ({task, selected, setSelected}) => {
Changed

2023-02-06 22:10 UTC, sschanzer commented on frontend/src/components/Tasks.tsx
> +
I was able to get it going.

2023-02-07 07:09 UTC, Kotauror commented on backend/todo_app/admin.py
> +from django.contrib import admin
Right, but it doesn't have to be committed. I think we figured it out in the convo above so I'm resolving this one.

2023-02-07 07:10 UTC, Kotauror commented on backend/todo_app/migrations/0001_initial.py
> +                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
Thank you for explaining!

2023-02-07 07:12 UTC, Kotauror commented on frontend/src/App.tsx
> +      setPendingTasks(response.pending)
It's a nitpick, but what would you say about `fetchTasks` ? It's a bit less wordy and doesn't include the name of the function you're calling (`getTasks`). Cause should the function (`getTasks`) ever be renamed or moved somewhere, the name `getResponseFromGetTasks` will stop making sense.

2023-02-07 07:14 UTC, Kotauror commented on frontend/src/components/Header.tsx
> +
I don't know either ;) But jokes aside, you should be able to run prettier as a command in the command line, after adding it to your project or installing Prettier plugin to your IDE.

2023-02-07 07:15 UTC, Kotauror approved these changes

2023-02-07 15:55 UTC, nadiacollado commented on frontend/src/Interfaces.tsx
> +export interface ITtask{
I don't think this is being used currently so should get deleted.

2023-02-07 16:01 UTC, nadiacollado commented on README.md
> +Make migragtions and migrate the models into the database
Oops missed this typo last time: "migrations"

2023-02-07 16:02 UTC, nadiacollado approved these changes

2023-02-07 18:19 UTC, sschanzer commented on backend/todo_app/views.py
> +    completedTasks = list(completedTasks)
Changed

2023-02-07 18:20 UTC, sschanzer commented on frontend/src/Interfaces.tsx
> +export interface ITtask{
Cool

2023-02-07 18:20 UTC, sschanzer commented on README.md
> +Make migragtions and migrate the models into the database
Changed

2023-02-07 18:37 UTC, merged